### ISSUE TITLE
EDA Panel or 2?

### ISSUE THREAD

**Issue by zbuckley** [gwu-data-mining-finalproject/Final-Project-GroupX#12]
Should we include a panel or 2 for EDA? and if so what sort of stuff do we want to put on there?

**Comment by PedroUria** [comment]
I guess we could include the distribution of ratings per user and per movie, which lead us to drop a few of both. And maybe some plots concerning the clustering of users, before running the models.

**Comment by zbuckley** [comment]
my list of EDA elements to include (based on downsampled dataset):
panel following netflix data:
1. histogram of ratings per user distribution
2. histogram of ratings per movie distribution
3. number of users and number of movies in downsampled dataset
???

panel following pedro clustering:
1) histogram of number of users per cluster?
2) number of clusters?
2) something indicating how much, if any, overlap between clusters?
3) average ratings for given movie (selected by dropdown) per each cluster?
   this could be cool... thinks its fairly doable too.
   thinking select movie from drop-down and up pops bar-graph with avg rating of each cluster
   (either horizontal/vertical bar graph prolly doesn't matter than much)
4) 2d plot of linreg solution/line over data points per selected user... or select cluster.. then user... then populate plot?

panel following aaron's collab filtering:
recommended movies per user? //hesitate on that b/c it seems more like model comparison page

@PedroUria @QuirkyDataScientist1978 we should discuss this a bit more

**Comment by QuirkyDataScientist1978** [comment]
I already have all of these metrics completed for my collaborative filtering (correlation) stuff. We can have a separate functioning panel for mine - then we can do a comparison panel maybe?
