### ISSUE TITLE
need gui-ready functions/classes for handling clustering

### ISSUE THREAD

**Issue by zbuckley** [gwu-data-mining-finalproject/Final-Project-GroupX#21]
Need to convert clustering code to gui compatible functions. see [issue 19](https://github.com/gwu-data-mining-finalproject/Final-Project-GroupX/issues/19) for the general pattern.

**Comment by QuirkyDataScientist1978** [comment]
I'm gonna need some help with this.

**Comment by zbuckley** [comment]
OBE
